LABEL_TO_SCHOOL_NAME = {
    "dhy": "宁波财经学院",
    "tsinghua": "清华大学",
    "pku": "北京大学",
    "renda": "中国人民大学",
    "beihang": "北京航空航天大学",
    "nbu": "宁波大学",
    "zhongchuan": "中国传媒大学",
    "beiyou": "北京邮电大学",
    "zhongnong": "中国农业大学",
    "beiwai": "北京外国语大学",
    "shoudujingmao": "首都经贸大学",
    "waijiao": "外交学院",
    "guoguan": "国际关系学院",
    "zhengfa": "中国政法大学",
    "nku": "南开大学",
    "tju(pyu)": "天津大学",
    "hbu": "河北大学",
    "china mit": "河北工业大学",
    "beifangxueyuan": "河北北方学院",
    "chengdeyixueyuan": "承德医学院",
    "sjz tdu": "石家庄铁道大学",
    "chongyou": "重庆邮电大学",
    "wanli": "浙江万里学院",
    "hangdian": "杭州电子科技大学",
    "wuqinggong": "武汉轻工大学",
}
